version: "3.2"

services:
  #  esb-auth:
  #    image: hengyi/esb-auth:${TAG}
  #    container_name: esb-auth
  #    restart: always
  #    volumes:
  #      - ./esb-auth:/home/esb/esb-auth
  #    expose:
  #      - 9998
  #    ports:
  #      - "9998:9998"
  #
  esb-sap:
    image: mcr.microsoft.com/java/jre:11u5-zulu-alpine
    container_name: esb-sap
    network_mode: host
    restart: always
    command: sh -c "java ${dd} -jar /home/esb/esb-sap/libs/2.0/esb-sap-fat.jar -conf /home/esb/esb-sap/config.json"
    volumes:
      - ./esb-sap:/home/esb/esb-sap
    expose:
      - 9997
      - 9876
    ports:
      - "9997:9997"
      - "9876:9876"

  loa-extra:
    image: mcr.microsoft.com/java/jre:11u3-zulu-alpine
    container_name: loa-extra
    network_mode: host
    restart: always
    command: sh -c "java -jar /home/esb/loa-extra/libs/${VER_LOA_EXTRA}/loa-extra-fat.jar"
    volumes:
      - ./loa-extra:/home/esb/loa-extra

  esb-oa:
    image: mcr.microsoft.com/java/jre:11u3-zulu-alpine
    container_name: esb-oa
    restart: always
    command: sh -c "java -jar /home/esb/esb-oa/libs/2.0/esb-oa-fat.jar -conf /home/esb/esb-oa/config.json"
    volumes:
      - ./esb-oa:/home/esb/esb-oa
    expose:
      - 9996
    ports:
      - "9996:9996"

  esb-open:
    image: mcr.microsoft.com/java/jre:11u3-zulu-alpine
    container_name: esb-open
    restart: always
    command: sh -c "java -jar /home/esb/esb-open/libs/2.0/esb-open-fat.jar -conf /home/esb/esb-open/config.json"
    volumes:
      - ./esb-open:/home/esb/esb-open
    expose:
      - 9999
    ports:
      - "9999:9999"